### ISSUE TITLE
Cliffgeneration

### ISSUE THREAD

**Issue by stefankinell** [rphlo/rusty-pullauta#9]
### Discussed in https://github.com/rphlo/rusty-pullauta/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **stefankinell** March 27, 2023</sup>
Did a first test.

Got an error when I came to the cliff generation:

```
Cliff generation 
Running makecliffs
thread 'main' panicked at 'range end index 13 out of range for slice of length 12', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/vec/mod.rs:2004:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```</div>

**Comment by stefankinell** [comment]
Transfered from discussions...

**Comment by stefankinell** [comment]
Unfortunately I still get

```
Vegetation generation
.................... done.
Cliff generation 
Running makecliffs
thread 'main' panicked at 'range end index 17 out of range for slice of length 16', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/vec/mod.rs:2004:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Rendering png map with depressions
...
```
This is the test file I am using: https://drive.google.com/file/d/1_mjZdj4eGmlI9cueEFQeWxzxdYeKjfqr/view?usp=share_link

It should render into this: https://kartor.gokartor.se/#13/7532491/718553

I even did a clean download and compilation into a new folder this time to make sure things were not messed up by my previous testing.
